version: "3"

services:
  db1:
    image: mysql:8
    volumes:
      - mysql1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: db
    ports:
      - 3301:3306
    ulimits:
      nproc: 65535
      nofile:
        soft: 4096
        hard: 4096
    mem_limit: 512m

  db2:
    image: mysql:8
    volumes:
      - mysql2:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password2
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: db
    ports:
      - 3302:3306
    ulimits:
      nproc: 65535
      nofile:
        soft: 4096
        hard: 4096
    mem_limit: 512m

volumes:
  mysql1:
  mysql2:
